#!/usr/bin/env python3
"""Generate HW06 API test-case JSON files and Excel-compatible CSV matrix."""
from __future__ import annotations

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "data" / "test-cases"
MATRIX_OUT = ROOT / "data" / "test-matrix.csv"

STUDENT_ID = "23127153"


def case(
    case_id: str,
    title: str,
    feature: str,
    method: str,
    endpoint: str,
    category: str,
    audit_label: str,
    expected_status: int,
    body: dict | None = None,
    headers: dict | None = None,
    preconditions: list[str] | None = None,
    expected_body_contains: list[str] | None = None,
    notes: str = "",
) -> dict:
    return {
        "id": case_id,
        "title": title,
        "feature": feature,
        "method": method,
        "endpoint": endpoint,
        "category": category,
        "auditLabel": audit_label,
        "preconditions": preconditions or [],
        "headers": headers or {"Content-Type": "application/json"},
        "body": body,
        "expectedStatus": expected_status,
        "expectedBodyContains": expected_body_contains or [],
        "notes": notes,
    }


def login_cases() -> list[dict]:
    feature = "FR-02"
    ep = "/api/login"
    ai = "ai-generated"
    ext = "student-extension"
    cases: list[dict] = [
        case("FR02-P01", "valid user login returns token", feature, "POST", ep, "positive", ai, 200,
             {"email": "test@eshop.com", "password": "Test1234!"},
             expected_body_contains=["token", "user", "Login successful"]),
        case("FR02-P02", "valid admin login returns admin role", feature, "POST", ep, "positive", ai, 200,
             {"email": "admin@eshop.com", "password": "Admin123!"},
             expected_body_contains=["token", "admin"]),
        case("FR02-P03", "response user object excludes password", feature, "POST", ep, "schema", ai, 200,
             {"email": "test@eshop.com", "password": "Test1234!"},
             notes="Assert password field absent in user object"),
        case("FR02-P04", "token is non-empty JWT string", feature, "POST", ep, "schema", ai, 200,
             {"email": "test@eshop.com", "password": "Test1234!"},
             notes="Token matches JWT pattern"),
        case("FR02-P05", "login resets lockout counters on success", feature, "POST", ep, "state", ai, 200,
             {"email": "test@eshop.com", "password": "Test1234!"},
             preconditions=["user had failed attempts but not locked"],
             notes="login_attempts should be 0 after success"),
        case("FR02-N01", "empty email rejected", feature, "POST", ep, "negative", ai, 401,
             {"email": "", "password": "Test1234!"},
             expected_body_contains=["error"]),
        case("FR02-N02", "empty password rejected", feature, "POST", ep, "negative", ai, 401,
             {"email": "test@eshop.com", "password": ""},
             expected_body_contains=["error"]),
        case("FR02-N03", "unknown email generic error", feature, "POST", ep, "negative", ai, 401,
             {"email": "nobody@eshop.com", "password": "Test1234!"},
             expected_body_contains=["Invalid email or password"]),
        case("FR02-N04", "wrong password generic error", feature, "POST", ep, "negative", ai, 401,
             {"email": "test@eshop.com", "password": "WrongPass1!"},
             expected_body_contains=["Invalid email or password"]),
        case("FR02-N05", "missing email field", feature, "POST", ep, "schema", ai, 401,
             {"password": "Test1234!"},
             expected_body_contains=["error"]),
        case("FR02-N06", "missing password field", feature, "POST", ep, "schema", ai, 401,
             {"email": "test@eshop.com"},
             expected_body_contains=["error"]),
        case("FR02-N07", "null email value", feature, "POST", ep, "schema", ai, 401,
             {"email": None, "password": "Test1234!"},
             expected_body_contains=["error"]),
        case("FR02-N08", "null password value", feature, "POST", ep, "schema", ai, 401,
             {"email": "test@eshop.com", "password": None},
             expected_body_contains=["error"]),
        case("FR02-N09", "invalid email format still hits API", feature, "POST", ep, "negative", ai, 401,
             {"email": "not-an-email", "password": "Test1234!"},
             expected_body_contains=["error"]),
        case("FR02-N10", "locked account returns 403", feature, "POST", ep, "state", ai, 403,
             {"email": "lockme@eshop.com", "password": "Test1234!"},
             preconditions=["register user lockme@eshop.com", "fail login 2 times to trigger lock"],
             expected_body_contains=["khóa"]),
        case("FR02-S01", "SQLi OR 1=1 in email", feature, "POST", ep, "security", ai, 401,
             {"email": "' OR '1'='1", "password": "Test1234!"},
             notes="Must not bypass authentication"),
        case("FR02-S02", "SQLi DROP TABLE in password", feature, "POST", ep, "security", ai, 401,
             {"email": "test@eshop.com", "password": "'; DROP TABLE users; --"},
             notes="Database must remain intact"),
        case("FR02-S03", "SQLi UNION SELECT in email", feature, "POST", ep, "security", ai, 401,
             {"email": "test@eshop.com' UNION SELECT 1,2,3--", "password": "x"},
             expected_body_contains=["error"]),
        case("FR02-S04", "XSS payload in email field", feature, "POST", ep, "security", ai, 401,
             {"email": "<script>alert(1)</script>@x.com", "password": "Test1234!"},
             notes="Response must not reflect unescaped script"),
        case("FR02-S05", "LDAP injection style email", feature, "POST", ep, "security", ai, 401,
             {"email": "admin@eshop.com)(&)", "password": "Admin123!"},
             expected_body_contains=["error"]),
        case("FR02-S06", "password field extremely long", feature, "POST", ep, "security", ai, 401,
             {"email": "test@eshop.com", "password": "A" * 10000},
             notes="Should not crash server"),
        case("FR02-D01", "email partition valid domain", feature, "POST", ep, "domain", ai, 200,
             {"email": "test@eshop.com", "password": "Test1234!"}),
        case("FR02-D02", "email partition subdomain", feature, "POST", ep, "domain", ai, 401,
             {"email": "user@mail.eshop.com", "password": "Test1234!"}),
        case("FR02-D03", "password case sensitive mismatch", feature, "POST", ep, "domain", ai, 401,
             {"email": "test@eshop.com", "password": "test1234!"}),
        case("FR02-D04", "email with plus addressing", feature, "POST", ep, "domain", ai, 401,
             {"email": "test+alias@eshop.com", "password": "Test1234!"},
             preconditions=["register test+alias@eshop.com if supported"]),
        case("FR02-D05", "whitespace-only password", feature, "POST", ep, "domain", ai, 401,
             {"email": "test@eshop.com", "password": "   "}),
        case("FR02-D06", "numeric password string", feature, "POST", ep, "domain", ai, 401,
             {"email": "test@eshop.com", "password": "12345678"}),
        case("FR02-D07", "email uppercase variant", feature, "POST", ep, "domain", ai, 401,
             {"email": "TEST@ESHOP.COM", "password": "Test1234!"},
             notes="SQLite default case sensitivity for email"),
        case("FR02-D08", "empty JSON body", feature, "POST", ep, "schema", ai, 401,
             {},
             expected_body_contains=["error"]),
        case("FR02-D09", "extra unknown fields ignored", feature, "POST", ep, "schema", ai, 200,
             {"email": "test@eshop.com", "password": "Test1234!", "rememberMe": True, "role": "admin"},
             notes="Extra role field must not elevate privileges"),
        case("FR02-D10", "double login same credentials", feature, "POST", ep, "state", ai, 200,
             {"email": "test@eshop.com", "password": "Test1234!"},
             notes="Second login should also succeed"),
        # Student extensions (5+)
        case("FR02-STU01", "leading space in email trimmed or rejected", feature, "POST", ep, "domain", ext, 401,
             {"email": " test@eshop.com", "password": "Test1234!"},
             notes="Student: boundary on email whitespace"),
        case("FR02-STU02", "trailing space in password", feature, "POST", ep, "domain", ext, 401,
             {"email": "test@eshop.com", "password": "Test1234! "},
             notes="Student: password exact match"),
        case("FR02-STU03", "login with Content-Type text/plain", feature, "POST", ep, "schema", ext, 400,
             {"email": "test@eshop.com", "password": "Test1234!"},
             headers={"Content-Type": "text/plain"},
             notes="Student: wrong content type"),
        case("FR02-STU04", "concurrent duplicate login requests", feature, "POST", ep, "state", ext, 200,
             {"email": "test@eshop.com", "password": "Test1234!"},
             notes="Student: both parallel requests should return 200"),
        case("FR02-STU05", "vietnamese diacritics in email local part", feature, "POST", ep, "domain", ext, 401,
             {"email": "nguyễn@eshop.com", "password": "Test1234!"},
             notes="Student: i18n email partition"),
        case("FR02-STU06", "password with emoji rejected", feature, "POST", ep, "domain", ext, 401,
             {"email": "test@eshop.com", "password": "Test1234!🔒"},
             notes="Student: unicode password edge"),
    ]
    return cases


def checkout_cases() -> list[dict]:
    feature = "FR-08"
    ep = "/api/checkout"
    ai = "ai-generated"
    ext = "student-extension"
    auth = {"Content-Type": "application/json", "Authorization": "Bearer {{userToken}}"}
    cases: list[dict] = [
        case("FR08-P01", "checkout with valid cart and address", feature, "POST", ep, "positive", ai, 200,
             {"total_amount": 6000000, "shipping_address": "123 Le Loi, Q1, TP.HCM"},
             headers=auth,
             preconditions=["login as test@eshop.com", "POST /api/cart with AirPods"],
             expected_body_contains=["Checkout successful", "orderId"]),
        case("FR08-P02", "order status pending after checkout", feature, "POST", ep, "state", ai, 200,
             {"total_amount": 6000000, "shipping_address": "123 Le Loi, Q1, TP.HCM"},
             headers=auth,
             preconditions=["login", "add single item to cart"],
             notes="Verify via GET /api/orders/my-orders status=pending"),
        case("FR08-P03", "checkout multiple cart items", feature, "POST", ep, "positive", ai, 200,
             {"total_amount": 36000000, "shipping_address": "456 Nguyen Hue, Q1"},
             headers=auth,
             preconditions=["login", "add iPhone and Samsung to cart"],
             expected_body_contains=["orderId"]),
        case("FR08-P04", "checkout with minimum valid address", feature, "POST", ep, "positive", ai, 200,
             {"total_amount": 6000000, "shipping_address": "A"},
             headers=auth,
             preconditions=["login", "cart has one item"]),
        case("FR08-P05", "checkout response includes numeric orderId", feature, "POST", ep, "schema", ai, 200,
             {"total_amount": 6000000, "shipping_address": "123 Le Loi"},
             headers=auth,
             preconditions=["login", "cart setup"],
             notes="orderId must be integer > 0"),
        case("FR08-N01", "checkout without Authorization header", feature, "POST", ep, "negative", ai, 401,
             {"total_amount": 6000000, "shipping_address": "123 Le Loi"},
             headers={"Content-Type": "application/json"},
             expected_body_contains=["Unauthorized"]),
        case("FR08-N02", "checkout with invalid token", feature, "POST", ep, "negative", ai, 403,
             {"total_amount": 6000000, "shipping_address": "123 Le Loi"},
             headers={"Content-Type": "application/json", "Authorization": "Bearer invalid.token.here"},
             expected_body_contains=["Forbidden"]),
        case("FR08-N03", "missing total_amount", feature, "POST", ep, "schema", ai, 200,
             {"shipping_address": "123 Le Loi"},
             headers=auth,
             preconditions=["login", "cart setup"],
             notes="SQLite may insert NULL — documents actual behavior"),
        case("FR08-N04", "missing shipping_address", feature, "POST", ep, "schema", ai, 200,
             {"total_amount": 6000000},
             headers=auth,
             preconditions=["login", "cart setup"]),
        case("FR08-N05", "empty shipping_address", feature, "POST", ep, "negative", ai, 200,
             {"total_amount": 6000000, "shipping_address": ""},
             headers=auth,
             preconditions=["login", "cart setup"]),
        case("FR08-N06", "negative total_amount", feature, "POST", ep, "negative", ai, 200,
             {"total_amount": -1000, "shipping_address": "123 Le Loi"},
             headers=auth,
             preconditions=["login", "cart setup"],
             notes="Business rule gap — order should not allow negative"),
        case("FR08-N07", "zero total_amount", feature, "POST", ep, "domain", ai, 200,
             {"total_amount": 0, "shipping_address": "123 Le Loi"},
             headers=auth,
             preconditions=["login", "cart setup"]),
        case("FR08-N08", "empty cart checkout", feature, "POST", ep, "state", ai, 200,
             {"total_amount": 0, "shipping_address": "123 Le Loi"},
             headers=auth,
             preconditions=["login", "empty cart"],
             notes="Still creates order — state transition test"),
        case("FR08-S01", "tampered total lower than cart sum", feature, "POST", ep, "security", ai, 200,
             {"total_amount": 1, "shipping_address": "123 Le Loi"},
             headers=auth,
             preconditions=["login", "cart total 6000000"],
             notes="IDOR/business logic — server does not validate total"),
        case("FR08-S02", "tampered total higher than cart sum", feature, "POST", ep, "security", ai, 200,
             {"total_amount": 999999999, "shipping_address": "123 Le Loi"},
             headers=auth,
             preconditions=["login", "cart setup"]),
        case("FR08-S03", "SQLi in shipping_address", feature, "POST", ep, "security", ai, 200,
             {"total_amount": 6000000, "shipping_address": "123'; DROP TABLE orders; --"},
             headers=auth,
             preconditions=["login", "cart setup"]),
        case("FR08-S04", "XSS in shipping_address stored", feature, "POST", ep, "security", ai, 200,
             {"total_amount": 6000000, "shipping_address": "<img src=x onerror=alert(1)>"},
             headers=auth,
             preconditions=["login", "cart setup"]),
        case("FR08-S05", "use another user token (IDOR)", feature, "POST", ep, "security", ai, 200,
             {"total_amount": 6000000, "shipping_address": "123 Le Loi"},
             headers={"Content-Type": "application/json", "Authorization": "Bearer {{otherUserToken}}"},
             preconditions=["login user A", "login user B", "user B cart setup", "send with user A token"],
             notes="Order should bind to token owner not cart owner"),
        case("FR08-D01", "total_amount as string number", feature, "POST", ep, "schema", ai, 200,
             {"total_amount": "6000000", "shipping_address": "123 Le Loi"},
             headers=auth,
             preconditions=["login", "cart setup"]),
        case("FR08-D02", "total_amount float value", feature, "POST", ep, "domain", ai, 200,
             {"total_amount": 6000000.5, "shipping_address": "123 Le Loi"},
             headers=auth,
             preconditions=["login", "cart setup"]),
        case("FR08-D03", "shipping_address as number type", feature, "POST", ep, "schema", ai, 200,
             {"total_amount": 6000000, "shipping_address": 12345},
             headers=auth,
             preconditions=["login", "cart setup"]),
        case("FR08-D04", "very long shipping address", feature, "POST", ep, "domain", ai, 200,
             {"total_amount": 6000000, "shipping_address": "X" * 2000},
             headers=auth,
             preconditions=["login", "cart setup"]),
        case("FR08-D05", "unicode vietnamese address", feature, "POST", ep, "domain", ai, 200,
             {"total_amount": 6000000, "shipping_address": "123 Đường Lê Lợi, Quận 1, TP.HCM"},
             headers=auth,
             preconditions=["login", "cart setup"]),
        case("FR08-D06", "extra coupon fields in body", feature, "POST", ep, "schema", ai, 200,
             {"total_amount": 6000000, "shipping_address": "123 Le Loi", "coupon": "SAVE10"},
             headers=auth,
             preconditions=["login", "cart setup"],
             notes="Coupon not applied at checkout API"),
        case("FR08-D07", "double checkout same cart", feature, "POST", ep, "state", ai, 200,
             {"total_amount": 6000000, "shipping_address": "123 Le Loi"},
             headers=auth,
             preconditions=["login", "cart setup", "checkout once", "checkout again"],
             notes="Creates duplicate orders — state test"),
        case("FR08-D08", "checkout then verify my-orders count", feature, "POST", ep, "state", ai, 200,
             {"total_amount": 6000000, "shipping_address": "123 Le Loi"},
             headers=auth,
             preconditions=["login", "cart setup"],
             notes="Order count increments by 1"),
        case("FR08-D09", "null total_amount", feature, "POST", ep, "schema", ai, 200,
             {"total_amount": None, "shipping_address": "123 Le Loi"},
             headers=auth,
             preconditions=["login", "cart setup"]),
        case("FR08-D10", "null shipping_address", feature, "POST", ep, "schema", ai, 200,
             {"total_amount": 6000000, "shipping_address": None},
             headers=auth,
             preconditions=["login", "cart setup"]),
        case("FR08-STU01", "checkout with expired JWT", feature, "POST", ep, "security", ext, 403,
             {"total_amount": 6000000, "shipping_address": "123 Le Loi"},
             headers={"Content-Type": "application/json", "Authorization": "Bearer {{expiredToken}}"},
             notes="Student: token expiry boundary"),
        case("FR08-STU02", "checkout address with newline chars", feature, "POST", ep, "domain", ext, 200,
             {"total_amount": 6000000, "shipping_address": "Line1\nLine2\r\nLine3"},
             headers=auth,
             preconditions=["login", "cart setup"]),
        case("FR08-STU03", "checkout after cart cleared manually", feature, "POST", ep, "state", ext, 200,
             {"total_amount": 6000000, "shipping_address": "123 Le Loi"},
             headers=auth,
             preconditions=["login", "add then clear cart via new session"],
             notes="Student: cart is in-memory per server restart"),
        case("FR08-STU04", "Bearer prefix missing in auth", feature, "POST", ep, "negative", ext, 401,
             {"total_amount": 6000000, "shipping_address": "123 Le Loi"},
             headers={"Content-Type": "application/json", "Authorization": "{{userToken}}"},
             notes="Student: malformed auth header"),
        case("FR08-STU05", "checkout with only whitespace address", feature, "POST", ep, "domain", ext, 200,
             {"total_amount": 6000000, "shipping_address": "   "},
             headers=auth,
             preconditions=["login", "cart setup"]),
        case("FR08-STU06", "total_amount scientific notation", feature, "POST", ep, "domain", ext, 200,
             {"total_amount": 6e6, "shipping_address": "123 Le Loi"},
             headers=auth,
             preconditions=["login", "cart setup"]),
    ]
    return cases


def admin_users_cases() -> list[dict]:
    feature = "FR-19"
    ai = "ai-generated"
    ext = "student-extension"
    admin_auth = {"Content-Type": "application/json", "Authorization": "Bearer {{adminToken}}"}
    user_auth = {"Content-Type": "application/json", "Authorization": "Bearer {{userToken}}"}
    cases: list[dict] = [
        case("FR19-P01", "admin lists all users", feature, "GET", "/api/admin/users", "positive", ai, 200,
             headers=admin_auth,
             preconditions=["login as admin@eshop.com"],
             expected_body_contains=["email", "role"]),
        case("FR19-P02", "list returns array of users", feature, "GET", "/api/admin/users", "schema", ai, 200,
             headers=admin_auth,
             preconditions=["admin token"],
             notes="Response is JSON array"),
        case("FR19-P03", "seed admin user present", feature, "GET", "/api/admin/users", "positive", ai, 200,
             headers=admin_auth,
             preconditions=["admin token"],
             expected_body_contains=["admin@eshop.com"]),
        case("FR19-P04", "seed test user present", feature, "GET", "/api/admin/users", "positive", ai, 200,
             headers=admin_auth,
             expected_body_contains=["test@eshop.com"]),
        case("FR19-P05", "user objects exclude password field", feature, "GET", "/api/admin/users", "schema", ai, 200,
             headers=admin_auth,
             notes="password must not appear in any element"),
        case("FR19-P06", "admin deletes disposable user", feature, "DELETE", "/api/admin/users/{{disposableUserId}}", "positive", ai, 200,
             headers=admin_auth,
             preconditions=["register disposable user", "admin token"],
             expected_body_contains=["User deleted"]),
        case("FR19-P07", "deleted user absent from list", feature, "GET", "/api/admin/users", "state", ai, 200,
             headers=admin_auth,
             preconditions=["delete user then list"],
             notes="Email no longer in response"),
        case("FR19-N01", "list users without token", feature, "GET", "/api/admin/users", "negative", ai, 401,
             headers={"Content-Type": "application/json"},
             expected_body_contains=["Unauthorized"]),
        case("FR19-N02", "list users invalid token", feature, "GET", "/api/admin/users", "negative", ai, 403,
             headers={"Content-Type": "application/json", "Authorization": "Bearer bad.token"},
             expected_body_contains=["Forbidden"]),
        case("FR19-N03", "delete user without token", feature, "DELETE", "/api/admin/users/99", "negative", ai, 401,
             headers={"Content-Type": "application/json"},
             expected_body_contains=["Unauthorized"]),
        case("FR19-N04", "delete user invalid token", feature, "DELETE", "/api/admin/users/99", "negative", ai, 403,
             headers={"Content-Type": "application/json", "Authorization": "Bearer bad.token"},
             expected_body_contains=["Forbidden"]),
        case("FR19-N05", "delete non-existent user id", feature, "DELETE", "/api/admin/users/999999", "negative", ai, 200,
             headers=admin_auth,
             notes="SUT returns 200 even when no row deleted"),
        case("FR19-S01", "regular user lists admin users (IDOR)", feature, "GET", "/api/admin/users", "security", ai, 200,
             headers=user_auth,
             preconditions=["login as test@eshop.com"],
             notes="No role check on backend — security gap"),
        case("FR19-S02", "regular user deletes another user (IDOR)", feature, "DELETE", "/api/admin/users/{{targetId}}", "security", ai, 200,
             headers=user_auth,
             preconditions=["login as test@eshop.com", "target disposable user"],
             notes="Privilege escalation gap"),
        case("FR19-S03", "SQLi in delete user id", feature, "DELETE", "/api/admin/users/1 OR 1=1", "security", ai, 404,
             headers=admin_auth,
             notes="Must not mass-delete users"),
        case("FR19-S04", "SQLi UNION in delete id path", feature, "DELETE", "/api/admin/users/1; DROP TABLE users;", "security", ai, 404,
             headers=admin_auth),
        case("FR19-S05", "negative user id in path", feature, "DELETE", "/api/admin/users/-1", "security", ai, 200,
             headers=admin_auth),
        case("FR19-D01", "list includes login_attempts field", feature, "GET", "/api/admin/users", "schema", ai, 200,
             headers=admin_auth,
             expected_body_contains=["login_attempts"]),
        case("FR19-D02", "list includes locked_until field", feature, "GET", "/api/admin/users", "schema", ai, 200,
             headers=admin_auth,
             expected_body_contains=["locked_until"]),
        case("FR19-D03", "delete id zero", feature, "DELETE", "/api/admin/users/0", "domain", ai, 200,
             headers=admin_auth),
        case("FR19-D04", "delete id non-numeric string", feature, "DELETE", "/api/admin/users/abc", "domain", ai, 404,
             headers=admin_auth),
        case("FR19-D05", "list response Content-Type json", feature, "GET", "/api/admin/users", "schema", ai, 200,
             headers=admin_auth,
             notes="Header Content-Type application/json"),
        case("FR19-D06", "admin deletes self", feature, "DELETE", "/api/admin/users/{{adminUserId}}", "state", ai, 200,
             headers=admin_auth,
             notes="Dangerous — admin removes own account"),
        case("FR19-D07", "double delete same user id", feature, "DELETE", "/api/admin/users/{{disposableUserId}}", "state", ai, 200,
             headers=admin_auth,
             preconditions=["delete once", "delete again"]),
        case("FR19-D08", "list after mass registration", feature, "GET", "/api/admin/users", "state", ai, 200,
             headers=admin_auth,
             preconditions=["register 3 new users"],
             notes="Array length increases"),
        case("FR19-D09", "user role values partition", feature, "GET", "/api/admin/users", "domain", ai, 200,
             headers=admin_auth,
             notes="Roles are admin or user only"),
        case("FR19-D10", "shipping_address field exposed", feature, "GET", "/api/admin/users", "schema", ai, 200,
             headers=admin_auth,
             expected_body_contains=["shipping_address"]),
        case("FR19-STU01", "GET with trailing slash variant", feature, "GET", "/api/admin/users/", "domain", ext, 404,
             headers=admin_auth,
             notes="Student: path normalization"),
        case("FR19-STU02", "DELETE with float id 1.5", feature, "DELETE", "/api/admin/users/1.5", "domain", ext, 404,
             headers=admin_auth),
        case("FR19-STU03", "list users with extra query param", feature, "GET", "/api/admin/users?role=admin", "domain", ext, 200,
             headers=admin_auth,
             notes="Student: filter not implemented — returns all"),
        case("FR19-STU04", "concurrent delete same user", feature, "DELETE", "/api/admin/users/{{disposableUserId}}", "state", ext, 200,
             headers=admin_auth,
             notes="Student: race condition"),
        case("FR19-STU05", "admin token after admin deleted", feature, "GET", "/api/admin/users", "state", ext, 200,
             headers=admin_auth,
             preconditions=["admin deletes self", "reuse old token"],
             notes="Student: stale token behavior"),
        case("FR19-STU06", "list with Accept text/html", feature, "GET", "/api/admin/users", "schema", ext, 200,
             headers={**admin_auth, "Accept": "text/html"},
             notes="Student: content negotiation"),
    ]
    return cases


def write_json(name: str, cases: list[dict]) -> None:
    path = OUT_DIR / name
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(cases, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"Wrote {len(cases)} cases -> {path}")


def export_matrix(all_cases: dict[str, list[dict]]) -> None:
  headers = [
      "StudentId", "CaseId", "Feature", "Title", "Method", "Endpoint",
      "Category", "AuditLabel", "ExpectedStatus", "Preconditions", "Notes"
  ]
  MATRIX_OUT.parent.mkdir(parents=True, exist_ok=True)
  with MATRIX_OUT.open("w", encoding="utf-8-sig", newline="") as f:
      writer = csv.DictWriter(f, fieldnames=headers)
      writer.writeheader()
      for cases in all_cases.values():
          for c in cases:
              writer.writerow({
                  "StudentId": STUDENT_ID,
                  "CaseId": c["id"],
                  "Feature": c["feature"],
                  "Title": c["title"],
                  "Method": c["method"],
                  "Endpoint": c["endpoint"],
                  "Category": c["category"],
                  "AuditLabel": c["auditLabel"],
                  "ExpectedStatus": c["expectedStatus"],
                  "Preconditions": "; ".join(c.get("preconditions", [])),
                  "Notes": c.get("notes", ""),
              })
  print(f"Wrote matrix -> {MATRIX_OUT}")


def main() -> None:
    all_cases = {
        "fr02-login.json": login_cases(),
        "fr08-checkout.json": checkout_cases(),
        "fr19-admin-users.json": admin_users_cases(),
    }
    for name, cases in all_cases.items():
        write_json(name, cases)
    export_matrix(all_cases)
    total = sum(len(v) for v in all_cases.values())
    ai_count = sum(1 for cases in all_cases.values() for c in cases if c["auditLabel"] == "ai-generated")
    ext_count = sum(1 for cases in all_cases.values() for c in cases if c["auditLabel"] == "student-extension")
    print(f"Total: {total} | AI: {ai_count} | Student extensions: {ext_count}")


if __name__ == "__main__":
    main()
